export const db = "main-stackoverflow"
export const questionColletion = "questions"
export const answerColletion = "answers"
export const commentsColletion = "comments"
export const voteColletion = "votes"
export const questionAttachmentBucket = "question-attachment"